package com.mdsproject.backend.models.enums;

public enum AuditAction {
    GROUP_CREATED,
    GROUP_JOINED,
    ROLE_CHANGED,
    WALLET_CREATED,
    ASSET_ADDED,
    TRANSACTION_CREATED,
    TRANSACTION_APPROVED,
    TRANSACTION_DECLINED,
    TRANSACTION_GROUP_CONSENSUS_REQUESTED,
    VIRTUAL_CARD_GENERATED,
    AUTO_APPROVE_THRESHOLD_CHANGED,
    SUB_WALLET_MEMBER_ASSIGNED,
    SUB_WALLET_MEMBER_REMOVED,
    AI_DECISION,
    RESOURCE_ALLOCATED,
    LIQUIDITY_WARNING,
    LEDGER_SWAP_EXECUTED
}
